// Code generated by internal/gen from protocol/wayland.xml. DO NOT EDIT.

package wl

import (
	"fmt"

	"qwertywm/wire"
)

// silence unused-import errors for protocols that never use fmt
var _ = fmt.Errorf

// ---------------------------------------------------------------------------
// wl_compositor
// ---------------------------------------------------------------------------

// CompositorName is the Wayland interface name of Compositor.
const CompositorName = "wl_compositor"

// CompositorVersion is the highest version of Compositor supported by these bindings.
const CompositorVersion = 6

// Compositor is a proxy for the wl_compositor interface.
type Compositor struct {
	wire.Proxy
}

// Interface returns the Wayland interface name "wl_compositor".
func (*Compositor) Interface() string { return "wl_compositor" }

// BindCompositor binds the global named name on the registry to a new Compositor.
// The version must be <= the advertised version and <= CompositorVersion.
func BindCompositor(r *wire.Registry, name uint32, version uint32) *Compositor {
	o := &Compositor{}
	r.Bind(name, CompositorName, version, o, &o.Proxy)
	return o
}

// CreateSurface: create new surface
func (o *Compositor) CreateSurface() *Surface {
	new_ := &Surface{}
	o.Conn().RegisterClient(new_, &new_.Proxy)
	e := &wire.Encoder{}
	e.PutUint(new_.ID())
	o.Conn().SendRequest(o, 0, e)
	return new_
}

// CreateRegion: create new region
func (o *Compositor) CreateRegion() *Region {
	new_ := &Region{}
	o.Conn().RegisterClient(new_, &new_.Proxy)
	e := &wire.Encoder{}
	e.PutUint(new_.ID())
	o.Conn().SendRequest(o, 1, e)
	return new_
}

// Dispatch decodes and dispatches an incoming event.
func (o *Compositor) Dispatch(opcode uint16, d *wire.Decoder) error {
	switch opcode {
	default:
		return fmt.Errorf("unknown opcode %d", opcode)
	}
}

// ---------------------------------------------------------------------------
// wl_shm_pool
// ---------------------------------------------------------------------------

// ShmPoolName is the Wayland interface name of ShmPool.
const ShmPoolName = "wl_shm_pool"

// ShmPoolVersion is the highest version of ShmPool supported by these bindings.
const ShmPoolVersion = 2

// ShmPool is a proxy for the wl_shm_pool interface.
type ShmPool struct {
	wire.Proxy
}

// Interface returns the Wayland interface name "wl_shm_pool".
func (*ShmPool) Interface() string { return "wl_shm_pool" }

// BindShmPool binds the global named name on the registry to a new ShmPool.
// The version must be <= the advertised version and <= ShmPoolVersion.
func BindShmPool(r *wire.Registry, name uint32, version uint32) *ShmPool {
	o := &ShmPool{}
	r.Bind(name, ShmPoolName, version, o, &o.Proxy)
	return o
}

// CreateBuffer: create a buffer from the pool
func (o *ShmPool) CreateBuffer(offset int32, width int32, height int32, stride int32, format ShmFormat) *Buffer {
	new_ := &Buffer{}
	o.Conn().RegisterClient(new_, &new_.Proxy)
	e := &wire.Encoder{}
	e.PutUint(new_.ID())
	e.PutInt(offset)
	e.PutInt(width)
	e.PutInt(height)
	e.PutInt(stride)
	e.PutUint(uint32(format))
	o.Conn().SendRequest(o, 0, e)
	return new_
}

// Destroy: destroy the pool
// Destroy is a destructor: the object is unusable after this call.
func (o *ShmPool) Destroy() {
	e := &wire.Encoder{}
	o.Conn().SendRequest(o, 1, e)
	o.Conn().Unregister(o)
}

// Resize: change the size of the pool mapping
func (o *ShmPool) Resize(size int32) {
	e := &wire.Encoder{}
	e.PutInt(size)
	o.Conn().SendRequest(o, 2, e)
}

// Dispatch decodes and dispatches an incoming event.
func (o *ShmPool) Dispatch(opcode uint16, d *wire.Decoder) error {
	switch opcode {
	default:
		return fmt.Errorf("unknown opcode %d", opcode)
	}
}

// ---------------------------------------------------------------------------
// wl_shm
// ---------------------------------------------------------------------------

// ShmName is the Wayland interface name of Shm.
const ShmName = "wl_shm"

// ShmVersion is the highest version of Shm supported by these bindings.
const ShmVersion = 2

// ShmError is the error enum.
type ShmError uint32

const (
	// ShmErrorInvalidFormat: buffer format is not known
	ShmErrorInvalidFormat ShmError = 0
	// ShmErrorInvalidStride: invalid size or stride during pool or buffer creation
	ShmErrorInvalidStride ShmError = 1
	// ShmErrorInvalidFd: mmapping the file descriptor failed
	ShmErrorInvalidFd ShmError = 2
)

// ShmFormat is the format enum.
type ShmFormat uint32

const (
	// ShmFormatArgb8888: 32-bit ARGB format, [31:0] A:R:G:B 8:8:8:8 little endian
	ShmFormatArgb8888 ShmFormat = 0
	// ShmFormatXrgb8888: 32-bit RGB format, [31:0] x:R:G:B 8:8:8:8 little endian
	ShmFormatXrgb8888 ShmFormat = 1
	// ShmFormatC8: 8-bit color index format, [7:0] C
	ShmFormatC8 ShmFormat = 0x20203843
	// ShmFormatRgb332: 8-bit RGB format, [7:0] R:G:B 3:3:2
	ShmFormatRgb332 ShmFormat = 0x38424752
	// ShmFormatBgr233: 8-bit BGR format, [7:0] B:G:R 2:3:3
	ShmFormatBgr233 ShmFormat = 0x38524742
	// ShmFormatXrgb4444: 16-bit xRGB format, [15:0] x:R:G:B 4:4:4:4 little endian
	ShmFormatXrgb4444 ShmFormat = 0x32315258
	// ShmFormatXbgr4444: 16-bit xBGR format, [15:0] x:B:G:R 4:4:4:4 little endian
	ShmFormatXbgr4444 ShmFormat = 0x32314258
	// ShmFormatRgbx4444: 16-bit RGBx format, [15:0] R:G:B:x 4:4:4:4 little endian
	ShmFormatRgbx4444 ShmFormat = 0x32315852
	// ShmFormatBgrx4444: 16-bit BGRx format, [15:0] B:G:R:x 4:4:4:4 little endian
	ShmFormatBgrx4444 ShmFormat = 0x32315842
	// ShmFormatArgb4444: 16-bit ARGB format, [15:0] A:R:G:B 4:4:4:4 little endian
	ShmFormatArgb4444 ShmFormat = 0x32315241
	// ShmFormatAbgr4444: 16-bit ABGR format, [15:0] A:B:G:R 4:4:4:4 little endian
	ShmFormatAbgr4444 ShmFormat = 0x32314241
	// ShmFormatRgba4444: 16-bit RBGA format, [15:0] R:G:B:A 4:4:4:4 little endian
	ShmFormatRgba4444 ShmFormat = 0x32314152
	// ShmFormatBgra4444: 16-bit BGRA format, [15:0] B:G:R:A 4:4:4:4 little endian
	ShmFormatBgra4444 ShmFormat = 0x32314142
	// ShmFormatXrgb1555: 16-bit xRGB format, [15:0] x:R:G:B 1:5:5:5 little endian
	ShmFormatXrgb1555 ShmFormat = 0x35315258
	// ShmFormatXbgr1555: 16-bit xBGR 1555 format, [15:0] x:B:G:R 1:5:5:5 little endian
	ShmFormatXbgr1555 ShmFormat = 0x35314258
	// ShmFormatRgbx5551: 16-bit RGBx 5551 format, [15:0] R:G:B:x 5:5:5:1 little endian
	ShmFormatRgbx5551 ShmFormat = 0x35315852
	// ShmFormatBgrx5551: 16-bit BGRx 5551 format, [15:0] B:G:R:x 5:5:5:1 little endian
	ShmFormatBgrx5551 ShmFormat = 0x35315842
	// ShmFormatArgb1555: 16-bit ARGB 1555 format, [15:0] A:R:G:B 1:5:5:5 little endian
	ShmFormatArgb1555 ShmFormat = 0x35315241
	// ShmFormatAbgr1555: 16-bit ABGR 1555 format, [15:0] A:B:G:R 1:5:5:5 little endian
	ShmFormatAbgr1555 ShmFormat = 0x35314241
	// ShmFormatRgba5551: 16-bit RGBA 5551 format, [15:0] R:G:B:A 5:5:5:1 little endian
	ShmFormatRgba5551 ShmFormat = 0x35314152
	// ShmFormatBgra5551: 16-bit BGRA 5551 format, [15:0] B:G:R:A 5:5:5:1 little endian
	ShmFormatBgra5551 ShmFormat = 0x35314142
	// ShmFormatRgb565: 16-bit RGB 565 format, [15:0] R:G:B 5:6:5 little endian
	ShmFormatRgb565 ShmFormat = 0x36314752
	// ShmFormatBgr565: 16-bit BGR 565 format, [15:0] B:G:R 5:6:5 little endian
	ShmFormatBgr565 ShmFormat = 0x36314742
	// ShmFormatRgb888: 24-bit RGB format, [23:0] R:G:B little endian
	ShmFormatRgb888 ShmFormat = 0x34324752
	// ShmFormatBgr888: 24-bit BGR format, [23:0] B:G:R little endian
	ShmFormatBgr888 ShmFormat = 0x34324742
	// ShmFormatXbgr8888: 32-bit xBGR format, [31:0] x:B:G:R 8:8:8:8 little endian
	ShmFormatXbgr8888 ShmFormat = 0x34324258
	// ShmFormatRgbx8888: 32-bit RGBx format, [31:0] R:G:B:x 8:8:8:8 little endian
	ShmFormatRgbx8888 ShmFormat = 0x34325852
	// ShmFormatBgrx8888: 32-bit BGRx format, [31:0] B:G:R:x 8:8:8:8 little endian
	ShmFormatBgrx8888 ShmFormat = 0x34325842
	// ShmFormatAbgr8888: 32-bit ABGR format, [31:0] A:B:G:R 8:8:8:8 little endian
	ShmFormatAbgr8888 ShmFormat = 0x34324241
	// ShmFormatRgba8888: 32-bit RGBA format, [31:0] R:G:B:A 8:8:8:8 little endian
	ShmFormatRgba8888 ShmFormat = 0x34324152
	// ShmFormatBgra8888: 32-bit BGRA format, [31:0] B:G:R:A 8:8:8:8 little endian
	ShmFormatBgra8888 ShmFormat = 0x34324142
	// ShmFormatXrgb2101010: 32-bit xRGB format, [31:0] x:R:G:B 2:10:10:10 little endian
	ShmFormatXrgb2101010 ShmFormat = 0x30335258
	// ShmFormatXbgr2101010: 32-bit xBGR format, [31:0] x:B:G:R 2:10:10:10 little endian
	ShmFormatXbgr2101010 ShmFormat = 0x30334258
	// ShmFormatRgbx1010102: 32-bit RGBx format, [31:0] R:G:B:x 10:10:10:2 little endian
	ShmFormatRgbx1010102 ShmFormat = 0x30335852
	// ShmFormatBgrx1010102: 32-bit BGRx format, [31:0] B:G:R:x 10:10:10:2 little endian
	ShmFormatBgrx1010102 ShmFormat = 0x30335842
	// ShmFormatArgb2101010: 32-bit ARGB format, [31:0] A:R:G:B 2:10:10:10 little endian
	ShmFormatArgb2101010 ShmFormat = 0x30335241
	// ShmFormatAbgr2101010: 32-bit ABGR format, [31:0] A:B:G:R 2:10:10:10 little endian
	ShmFormatAbgr2101010 ShmFormat = 0x30334241
	// ShmFormatRgba1010102: 32-bit RGBA format, [31:0] R:G:B:A 10:10:10:2 little endian
	ShmFormatRgba1010102 ShmFormat = 0x30334152
	// ShmFormatBgra1010102: 32-bit BGRA format, [31:0] B:G:R:A 10:10:10:2 little endian
	ShmFormatBgra1010102 ShmFormat = 0x30334142
	// ShmFormatYuyv: packed YCbCr format, [31:0] Cr0:Y1:Cb0:Y0 8:8:8:8 little endian
	ShmFormatYuyv ShmFormat = 0x56595559
	// ShmFormatYvyu: packed YCbCr format, [31:0] Cb0:Y1:Cr0:Y0 8:8:8:8 little endian
	ShmFormatYvyu ShmFormat = 0x55595659
	// ShmFormatUyvy: packed YCbCr format, [31:0] Y1:Cr0:Y0:Cb0 8:8:8:8 little endian
	ShmFormatUyvy ShmFormat = 0x59565955
	// ShmFormatVyuy: packed YCbCr format, [31:0] Y1:Cb0:Y0:Cr0 8:8:8:8 little endian
	ShmFormatVyuy ShmFormat = 0x59555956
	// ShmFormatAyuv: packed AYCbCr format, [31:0] A:Y:Cb:Cr 8:8:8:8 little endian
	ShmFormatAyuv ShmFormat = 0x56555941
	// ShmFormatNv12: 2 plane YCbCr Cr:Cb format, 2x2 subsampled Cr:Cb plane
	ShmFormatNv12 ShmFormat = 0x3231564e
	// ShmFormatNv21: 2 plane YCbCr Cb:Cr format, 2x2 subsampled Cb:Cr plane
	ShmFormatNv21 ShmFormat = 0x3132564e
	// ShmFormatNv16: 2 plane YCbCr Cr:Cb format, 2x1 subsampled Cr:Cb plane
	ShmFormatNv16 ShmFormat = 0x3631564e
	// ShmFormatNv61: 2 plane YCbCr Cb:Cr format, 2x1 subsampled Cb:Cr plane
	ShmFormatNv61 ShmFormat = 0x3136564e
	// ShmFormatYuv410: 3 plane YCbCr format, 4x4 subsampled Cb (1) and Cr (2) planes
	ShmFormatYuv410 ShmFormat = 0x39565559
	// ShmFormatYvu410: 3 plane YCbCr format, 4x4 subsampled Cr (1) and Cb (2) planes
	ShmFormatYvu410 ShmFormat = 0x39555659
	// ShmFormatYuv411: 3 plane YCbCr format, 4x1 subsampled Cb (1) and Cr (2) planes
	ShmFormatYuv411 ShmFormat = 0x31315559
	// ShmFormatYvu411: 3 plane YCbCr format, 4x1 subsampled Cr (1) and Cb (2) planes
	ShmFormatYvu411 ShmFormat = 0x31315659
	// ShmFormatYuv420: 3 plane YCbCr format, 2x2 subsampled Cb (1) and Cr (2) planes
	ShmFormatYuv420 ShmFormat = 0x32315559
	// ShmFormatYvu420: 3 plane YCbCr format, 2x2 subsampled Cr (1) and Cb (2) planes
	ShmFormatYvu420 ShmFormat = 0x32315659
	// ShmFormatYuv422: 3 plane YCbCr format, 2x1 subsampled Cb (1) and Cr (2) planes
	ShmFormatYuv422 ShmFormat = 0x36315559
	// ShmFormatYvu422: 3 plane YCbCr format, 2x1 subsampled Cr (1) and Cb (2) planes
	ShmFormatYvu422 ShmFormat = 0x36315659
	// ShmFormatYuv444: 3 plane YCbCr format, non-subsampled Cb (1) and Cr (2) planes
	ShmFormatYuv444 ShmFormat = 0x34325559
	// ShmFormatYvu444: 3 plane YCbCr format, non-subsampled Cr (1) and Cb (2) planes
	ShmFormatYvu444 ShmFormat = 0x34325659
	// ShmFormatR8: [7:0] R
	ShmFormatR8 ShmFormat = 0x20203852
	// ShmFormatR16: [15:0] R little endian
	ShmFormatR16 ShmFormat = 0x20363152
	// ShmFormatRg88: [15:0] R:G 8:8 little endian
	ShmFormatRg88 ShmFormat = 0x38384752
	// ShmFormatGr88: [15:0] G:R 8:8 little endian
	ShmFormatGr88 ShmFormat = 0x38385247
	// ShmFormatRg1616: [31:0] R:G 16:16 little endian
	ShmFormatRg1616 ShmFormat = 0x32334752
	// ShmFormatGr1616: [31:0] G:R 16:16 little endian
	ShmFormatGr1616 ShmFormat = 0x32335247
	// ShmFormatXrgb16161616f: [63:0] x:R:G:B 16:16:16:16 little endian
	ShmFormatXrgb16161616f ShmFormat = 0x48345258
	// ShmFormatXbgr16161616f: [63:0] x:B:G:R 16:16:16:16 little endian
	ShmFormatXbgr16161616f ShmFormat = 0x48344258
	// ShmFormatArgb16161616f: [63:0] A:R:G:B 16:16:16:16 little endian
	ShmFormatArgb16161616f ShmFormat = 0x48345241
	// ShmFormatAbgr16161616f: [63:0] A:B:G:R 16:16:16:16 little endian
	ShmFormatAbgr16161616f ShmFormat = 0x48344241
	// ShmFormatXyuv8888: [31:0] X:Y:Cb:Cr 8:8:8:8 little endian
	ShmFormatXyuv8888 ShmFormat = 0x56555958
	// ShmFormatVuy888: [23:0] Cr:Cb:Y 8:8:8 little endian
	ShmFormatVuy888 ShmFormat = 0x34325556
	// ShmFormatVuy101010: Y followed by U then V, 10:10:10. Non-linear modifier only
	ShmFormatVuy101010 ShmFormat = 0x30335556
	// ShmFormatY210: [63:0] Cr0:0:Y1:0:Cb0:0:Y0:0 10:6:10:6:10:6:10:6 little endian per 2 Y pixels
	ShmFormatY210 ShmFormat = 0x30313259
	// ShmFormatY212: [63:0] Cr0:0:Y1:0:Cb0:0:Y0:0 12:4:12:4:12:4:12:4 little endian per 2 Y pixels
	ShmFormatY212 ShmFormat = 0x32313259
	// ShmFormatY216: [63:0] Cr0:Y1:Cb0:Y0 16:16:16:16 little endian per 2 Y pixels
	ShmFormatY216 ShmFormat = 0x36313259
	// ShmFormatY410: [31:0] A:Cr:Y:Cb 2:10:10:10 little endian
	ShmFormatY410 ShmFormat = 0x30313459
	// ShmFormatY412: [63:0] A:0:Cr:0:Y:0:Cb:0 12:4:12:4:12:4:12:4 little endian
	ShmFormatY412 ShmFormat = 0x32313459
	// ShmFormatY416: [63:0] A:Cr:Y:Cb 16:16:16:16 little endian
	ShmFormatY416 ShmFormat = 0x36313459
	// ShmFormatXvyu2101010: [31:0] X:Cr:Y:Cb 2:10:10:10 little endian
	ShmFormatXvyu2101010 ShmFormat = 0x30335658
	// ShmFormatXvyu1216161616: [63:0] X:0:Cr:0:Y:0:Cb:0 12:4:12:4:12:4:12:4 little endian
	ShmFormatXvyu1216161616 ShmFormat = 0x36335658
	// ShmFormatXvyu16161616: [63:0] X:Cr:Y:Cb 16:16:16:16 little endian
	ShmFormatXvyu16161616 ShmFormat = 0x38345658
	// ShmFormatY0l0: [63:0]   A3:A2:Y3:0:Cr0:0:Y2:0:A1:A0:Y1:0:Cb0:0:Y0:0  1:1:8:2:8:2:8:2:1:1:8:2:8:2:8:2 little endian
	ShmFormatY0l0 ShmFormat = 0x304c3059
	// ShmFormatX0l0: [63:0]   X3:X2:Y3:0:Cr0:0:Y2:0:X1:X0:Y1:0:Cb0:0:Y0:0  1:1:8:2:8:2:8:2:1:1:8:2:8:2:8:2 little endian
	ShmFormatX0l0 ShmFormat = 0x304c3058
	// ShmFormatY0l2: [63:0]   A3:A2:Y3:Cr0:Y2:A1:A0:Y1:Cb0:Y0  1:1:10:10:10:1:1:10:10:10 little endian
	ShmFormatY0l2 ShmFormat = 0x324c3059
	// ShmFormatX0l2: [63:0]   X3:X2:Y3:Cr0:Y2:X1:X0:Y1:Cb0:Y0  1:1:10:10:10:1:1:10:10:10 little endian
	ShmFormatX0l2        ShmFormat = 0x324c3058
	ShmFormatYuv4208bit  ShmFormat = 0x38305559
	ShmFormatYuv42010bit ShmFormat = 0x30315559
	ShmFormatXrgb8888A8  ShmFormat = 0x38415258
	ShmFormatXbgr8888A8  ShmFormat = 0x38414258
	ShmFormatRgbx8888A8  ShmFormat = 0x38415852
	ShmFormatBgrx8888A8  ShmFormat = 0x38415842
	ShmFormatRgb888A8    ShmFormat = 0x38413852
	ShmFormatBgr888A8    ShmFormat = 0x38413842
	ShmFormatRgb565A8    ShmFormat = 0x38413552
	ShmFormatBgr565A8    ShmFormat = 0x38413542
	// ShmFormatNv24: non-subsampled Cr:Cb plane
	ShmFormatNv24 ShmFormat = 0x3432564e
	// ShmFormatNv42: non-subsampled Cb:Cr plane
	ShmFormatNv42 ShmFormat = 0x3234564e
	// ShmFormatP210: 2x1 subsampled Cr:Cb plane, 10 bit per channel
	ShmFormatP210 ShmFormat = 0x30313250
	// ShmFormatP010: 2x2 subsampled Cr:Cb plane 10 bits per channel
	ShmFormatP010 ShmFormat = 0x30313050
	// ShmFormatP012: 2x2 subsampled Cr:Cb plane 12 bits per channel
	ShmFormatP012 ShmFormat = 0x32313050
	// ShmFormatP016: 2x2 subsampled Cr:Cb plane 16 bits per channel
	ShmFormatP016 ShmFormat = 0x36313050
	// ShmFormatAxbxgxrx106106106106: [63:0] A:x:B:x:G:x:R:x 10:6:10:6:10:6:10:6 little endian
	ShmFormatAxbxgxrx106106106106 ShmFormat = 0x30314241
	// ShmFormatNv15: 2x2 subsampled Cr:Cb plane
	ShmFormatNv15 ShmFormat = 0x3531564e
	ShmFormatQ410 ShmFormat = 0x30313451
	ShmFormatQ401 ShmFormat = 0x31303451
	// ShmFormatXrgb16161616: [63:0] x:R:G:B 16:16:16:16 little endian
	ShmFormatXrgb16161616 ShmFormat = 0x38345258
	// ShmFormatXbgr16161616: [63:0] x:B:G:R 16:16:16:16 little endian
	ShmFormatXbgr16161616 ShmFormat = 0x38344258
	// ShmFormatArgb16161616: [63:0] A:R:G:B 16:16:16:16 little endian
	ShmFormatArgb16161616 ShmFormat = 0x38345241
	// ShmFormatAbgr16161616: [63:0] A:B:G:R 16:16:16:16 little endian
	ShmFormatAbgr16161616 ShmFormat = 0x38344241
	// ShmFormatC1: [7:0] C0:C1:C2:C3:C4:C5:C6:C7 1:1:1:1:1:1:1:1 eight pixels/byte
	ShmFormatC1 ShmFormat = 0x20203143
	// ShmFormatC2: [7:0] C0:C1:C2:C3 2:2:2:2 four pixels/byte
	ShmFormatC2 ShmFormat = 0x20203243
	// ShmFormatC4: [7:0] C0:C1 4:4 two pixels/byte
	ShmFormatC4 ShmFormat = 0x20203443
	// ShmFormatD1: [7:0] D0:D1:D2:D3:D4:D5:D6:D7 1:1:1:1:1:1:1:1 eight pixels/byte
	ShmFormatD1 ShmFormat = 0x20203144
	// ShmFormatD2: [7:0] D0:D1:D2:D3 2:2:2:2 four pixels/byte
	ShmFormatD2 ShmFormat = 0x20203244
	// ShmFormatD4: [7:0] D0:D1 4:4 two pixels/byte
	ShmFormatD4 ShmFormat = 0x20203444
	// ShmFormatD8: [7:0] D
	ShmFormatD8 ShmFormat = 0x20203844
	// ShmFormatR1: [7:0] R0:R1:R2:R3:R4:R5:R6:R7 1:1:1:1:1:1:1:1 eight pixels/byte
	ShmFormatR1 ShmFormat = 0x20203152
	// ShmFormatR2: [7:0] R0:R1:R2:R3 2:2:2:2 four pixels/byte
	ShmFormatR2 ShmFormat = 0x20203252
	// ShmFormatR4: [7:0] R0:R1 4:4 two pixels/byte
	ShmFormatR4 ShmFormat = 0x20203452
	// ShmFormatR10: [15:0] x:R 6:10 little endian
	ShmFormatR10 ShmFormat = 0x20303152
	// ShmFormatR12: [15:0] x:R 4:12 little endian
	ShmFormatR12 ShmFormat = 0x20323152
	// ShmFormatAvuy8888: [31:0] A:Cr:Cb:Y 8:8:8:8 little endian
	ShmFormatAvuy8888 ShmFormat = 0x59555641
	// ShmFormatXvuy8888: [31:0] X:Cr:Cb:Y 8:8:8:8 little endian
	ShmFormatXvuy8888 ShmFormat = 0x59555658
	// ShmFormatP030: 2x2 subsampled Cr:Cb plane 10 bits per channel packed
	ShmFormatP030 ShmFormat = 0x30333050
)

// Shm is a proxy for the wl_shm interface.
type Shm struct {
	wire.Proxy

	// OnFormat: pixel format description
	OnFormat func(format ShmFormat)
}

// Interface returns the Wayland interface name "wl_shm".
func (*Shm) Interface() string { return "wl_shm" }

// BindShm binds the global named name on the registry to a new Shm.
// The version must be <= the advertised version and <= ShmVersion.
func BindShm(r *wire.Registry, name uint32, version uint32) *Shm {
	o := &Shm{}
	r.Bind(name, ShmName, version, o, &o.Proxy)
	return o
}

// CreatePool: create a shm pool
func (o *Shm) CreatePool(fd int, size int32) *ShmPool {
	new_ := &ShmPool{}
	o.Conn().RegisterClient(new_, &new_.Proxy)
	e := &wire.Encoder{}
	e.PutUint(new_.ID())
	e.PutFd(fd)
	e.PutInt(size)
	o.Conn().SendRequest(o, 0, e)
	return new_
}

// Release: release the shm object
// Release is a destructor: the object is unusable after this call.
func (o *Shm) Release() {
	e := &wire.Encoder{}
	o.Conn().SendRequest(o, 1, e)
	o.Conn().Unregister(o)
}

// Dispatch decodes and dispatches an incoming event.
func (o *Shm) Dispatch(opcode uint16, d *wire.Decoder) error {
	switch opcode {
	case 0: // format
		a0Raw, err := d.Uint()
		if err != nil {
			return err
		}
		a0 := ShmFormat(a0Raw)
		if o.OnFormat != nil {
			o.OnFormat(a0)
		}
		_ = a0
		return nil
	default:
		return fmt.Errorf("unknown opcode %d", opcode)
	}
}

// ---------------------------------------------------------------------------
// wl_buffer
// ---------------------------------------------------------------------------

// BufferName is the Wayland interface name of Buffer.
const BufferName = "wl_buffer"

// BufferVersion is the highest version of Buffer supported by these bindings.
const BufferVersion = 1

// Buffer is a proxy for the wl_buffer interface.
type Buffer struct {
	wire.Proxy

	// OnRelease: compositor releases buffer
	OnRelease func()
}

// Interface returns the Wayland interface name "wl_buffer".
func (*Buffer) Interface() string { return "wl_buffer" }

// BindBuffer binds the global named name on the registry to a new Buffer.
// The version must be <= the advertised version and <= BufferVersion.
func BindBuffer(r *wire.Registry, name uint32, version uint32) *Buffer {
	o := &Buffer{}
	r.Bind(name, BufferName, version, o, &o.Proxy)
	return o
}

// Destroy: destroy a buffer
// Destroy is a destructor: the object is unusable after this call.
func (o *Buffer) Destroy() {
	e := &wire.Encoder{}
	o.Conn().SendRequest(o, 0, e)
	o.Conn().Unregister(o)
}

// Dispatch decodes and dispatches an incoming event.
func (o *Buffer) Dispatch(opcode uint16, d *wire.Decoder) error {
	switch opcode {
	case 0: // release
		if o.OnRelease != nil {
			o.OnRelease()
		}
		return nil
	default:
		return fmt.Errorf("unknown opcode %d", opcode)
	}
}

// ---------------------------------------------------------------------------
// wl_data_offer
// ---------------------------------------------------------------------------

// DataOfferName is the Wayland interface name of DataOffer.
const DataOfferName = "wl_data_offer"

// DataOfferVersion is the highest version of DataOffer supported by these bindings.
const DataOfferVersion = 3

// DataOfferError is the error enum.
type DataOfferError uint32

const (
	// DataOfferErrorInvalidFinish: finish request was called untimely
	DataOfferErrorInvalidFinish DataOfferError = 0
	// DataOfferErrorInvalidActionMask: action mask contains invalid values
	DataOfferErrorInvalidActionMask DataOfferError = 1
	// DataOfferErrorInvalidAction: action argument has an invalid value
	DataOfferErrorInvalidAction DataOfferError = 2
	// DataOfferErrorInvalidOffer: offer doesn't accept this request
	DataOfferErrorInvalidOffer DataOfferError = 3
)

// DataOffer is a proxy for the wl_data_offer interface.
type DataOffer struct {
	wire.Proxy

	// OnOffer: advertise offered mime type
	OnOffer func(mimeType string)

	// OnSourceActions: notify the source-side available actions
	OnSourceActions func(sourceActions DataDeviceManagerDndAction)

	// OnAction: notify the selected action
	OnAction func(dndAction DataDeviceManagerDndAction)
}

// Interface returns the Wayland interface name "wl_data_offer".
func (*DataOffer) Interface() string { return "wl_data_offer" }

// BindDataOffer binds the global named name on the registry to a new DataOffer.
// The version must be <= the advertised version and <= DataOfferVersion.
func BindDataOffer(r *wire.Registry, name uint32, version uint32) *DataOffer {
	o := &DataOffer{}
	r.Bind(name, DataOfferName, version, o, &o.Proxy)
	return o
}

// Accept: accept one of the offered mime types
func (o *DataOffer) Accept(serial uint32, mimeType string) {
	e := &wire.Encoder{}
	e.PutUint(serial)
	e.PutString(mimeType)
	o.Conn().SendRequest(o, 0, e)
}

// Receive: request that the data is transferred
func (o *DataOffer) Receive(mimeType string, fd int) {
	e := &wire.Encoder{}
	e.PutString(mimeType)
	e.PutFd(fd)
	o.Conn().SendRequest(o, 1, e)
}

// Destroy: destroy data offer
// Destroy is a destructor: the object is unusable after this call.
func (o *DataOffer) Destroy() {
	e := &wire.Encoder{}
	o.Conn().SendRequest(o, 2, e)
	o.Conn().Unregister(o)
}

// Finish: the offer will no longer be used
func (o *DataOffer) Finish() {
	e := &wire.Encoder{}
	o.Conn().SendRequest(o, 3, e)
}

// SetActions: set the available/preferred drag-and-drop actions
func (o *DataOffer) SetActions(dndActions DataDeviceManagerDndAction, preferredAction DataDeviceManagerDndAction) {
	e := &wire.Encoder{}
	e.PutUint(uint32(dndActions))
	e.PutUint(uint32(preferredAction))
	o.Conn().SendRequest(o, 4, e)
}

// Dispatch decodes and dispatches an incoming event.
func (o *DataOffer) Dispatch(opcode uint16, d *wire.Decoder) error {
	switch opcode {
	case 0: // offer
		a0, _, err := d.String()
		if err != nil {
			return err
		}
		if o.OnOffer != nil {
			o.OnOffer(a0)
		}
		_ = a0
		return nil
	case 1: // source_actions
		a0Raw, err := d.Uint()
		if err != nil {
			return err
		}
		a0 := DataDeviceManagerDndAction(a0Raw)
		if o.OnSourceActions != nil {
			o.OnSourceActions(a0)
		}
		_ = a0
		return nil
	case 2: // action
		a0Raw, err := d.Uint()
		if err != nil {
			return err
		}
		a0 := DataDeviceManagerDndAction(a0Raw)
		if o.OnAction != nil {
			o.OnAction(a0)
		}
		_ = a0
		return nil
	default:
		return fmt.Errorf("unknown opcode %d", opcode)
	}
}

// ---------------------------------------------------------------------------
// wl_data_source
// ---------------------------------------------------------------------------

// DataSourceName is the Wayland interface name of DataSource.
const DataSourceName = "wl_data_source"

// DataSourceVersion is the highest version of DataSource supported by these bindings.
const DataSourceVersion = 3

// DataSourceError is the error enum.
type DataSourceError uint32

const (
	// DataSourceErrorInvalidActionMask: action mask contains invalid values
	DataSourceErrorInvalidActionMask DataSourceError = 0
	// DataSourceErrorInvalidSource: source doesn't accept this request
	DataSourceErrorInvalidSource DataSourceError = 1
)

// DataSource is a proxy for the wl_data_source interface.
type DataSource struct {
	wire.Proxy

	// OnTarget: a target accepts an offered mime type
	OnTarget func(mimeType string)

	// OnSend: send the data
	OnSend func(mimeType string, fd int)

	// OnCancelled: selection was cancelled
	OnCancelled func()

	// OnDndDropPerformed: the drag-and-drop operation physically finished
	OnDndDropPerformed func()

	// OnDndFinished: the drag-and-drop operation concluded
	OnDndFinished func()

	// OnAction: notify the selected action
	OnAction func(dndAction DataDeviceManagerDndAction)
}

// Interface returns the Wayland interface name "wl_data_source".
func (*DataSource) Interface() string { return "wl_data_source" }

// BindDataSource binds the global named name on the registry to a new DataSource.
// The version must be <= the advertised version and <= DataSourceVersion.
func BindDataSource(r *wire.Registry, name uint32, version uint32) *DataSource {
	o := &DataSource{}
	r.Bind(name, DataSourceName, version, o, &o.Proxy)
	return o
}

// Offer: add an offered mime type
func (o *DataSource) Offer(mimeType string) {
	e := &wire.Encoder{}
	e.PutString(mimeType)
	o.Conn().SendRequest(o, 0, e)
}

// Destroy: destroy the data source
// Destroy is a destructor: the object is unusable after this call.
func (o *DataSource) Destroy() {
	e := &wire.Encoder{}
	o.Conn().SendRequest(o, 1, e)
	o.Conn().Unregister(o)
}

// SetActions: set the available drag-and-drop actions
func (o *DataSource) SetActions(dndActions DataDeviceManagerDndAction) {
	e := &wire.Encoder{}
	e.PutUint(uint32(dndActions))
	o.Conn().SendRequest(o, 2, e)
}

// Dispatch decodes and dispatches an incoming event.
func (o *DataSource) Dispatch(opcode uint16, d *wire.Decoder) error {
	switch opcode {
	case 0: // target
		a0, _, err := d.String()
		if err != nil {
			return err
		}
		if o.OnTarget != nil {
			o.OnTarget(a0)
		}
		_ = a0
		return nil
	case 1: // send
		a0, _, err := d.String()
		if err != nil {
			return err
		}
		a1, err := d.Fd()
		if err != nil {
			return err
		}
		if o.OnSend != nil {
			o.OnSend(a0, a1)
		}
		_ = a0
		_ = a1
		return nil
	case 2: // cancelled
		if o.OnCancelled != nil {
			o.OnCancelled()
		}
		return nil
	case 3: // dnd_drop_performed
		if o.OnDndDropPerformed != nil {
			o.OnDndDropPerformed()
		}
		return nil
	case 4: // dnd_finished
		if o.OnDndFinished != nil {
			o.OnDndFinished()
		}
		return nil
	case 5: // action
		a0Raw, err := d.Uint()
		if err != nil {
			return err
		}
		a0 := DataDeviceManagerDndAction(a0Raw)
		if o.OnAction != nil {
			o.OnAction(a0)
		}
		_ = a0
		return nil
	default:
		return fmt.Errorf("unknown opcode %d", opcode)
	}
}

// ---------------------------------------------------------------------------
// wl_data_device
// ---------------------------------------------------------------------------

// DataDeviceName is the Wayland interface name of DataDevice.
const DataDeviceName = "wl_data_device"

// DataDeviceVersion is the highest version of DataDevice supported by these bindings.
const DataDeviceVersion = 3

// DataDeviceError is the error enum.
type DataDeviceError uint32

const (
	// DataDeviceErrorRole: given wl_surface has another role
	DataDeviceErrorRole DataDeviceError = 0
	// DataDeviceErrorUsedSource: source has already been used
	DataDeviceErrorUsedSource DataDeviceError = 1
)

// DataDevice is a proxy for the wl_data_device interface.
type DataDevice struct {
	wire.Proxy

	// OnDataOffer: introduce a new wl_data_offer
	OnDataOffer func(id *DataOffer)

	// OnEnter: initiate drag-and-drop session
	OnEnter func(serial uint32, surface *Surface, x wire.Fixed, y wire.Fixed, id *DataOffer)

	// OnLeave: end drag-and-drop session
	OnLeave func()

	// OnMotion: drag-and-drop session motion
	OnMotion func(time uint32, x wire.Fixed, y wire.Fixed)

	// OnDrop: end drag-and-drop session successfully
	OnDrop func()

	// OnSelection: advertise new selection
	OnSelection func(id *DataOffer)
}

// Interface returns the Wayland interface name "wl_data_device".
func (*DataDevice) Interface() string { return "wl_data_device" }

// BindDataDevice binds the global named name on the registry to a new DataDevice.
// The version must be <= the advertised version and <= DataDeviceVersion.
func BindDataDevice(r *wire.Registry, name uint32, version uint32) *DataDevice {
	o := &DataDevice{}
	r.Bind(name, DataDeviceName, version, o, &o.Proxy)
	return o
}

// StartDrag: start drag-and-drop operation
func (o *DataDevice) StartDrag(source *DataSource, origin *Surface, icon *Surface, serial uint32) {
	e := &wire.Encoder{}
	e.PutObject(wire.ObjectID(source))
	e.PutObject(wire.ObjectID(origin))
	e.PutObject(wire.ObjectID(icon))
	e.PutUint(serial)
	o.Conn().SendRequest(o, 0, e)
}

// SetSelection: copy data to the selection
func (o *DataDevice) SetSelection(source *DataSource, serial uint32) {
	e := &wire.Encoder{}
	e.PutObject(wire.ObjectID(source))
	e.PutUint(serial)
	o.Conn().SendRequest(o, 1, e)
}

// Release: destroy data device
// Release is a destructor: the object is unusable after this call.
func (o *DataDevice) Release() {
	e := &wire.Encoder{}
	o.Conn().SendRequest(o, 2, e)
	o.Conn().Unregister(o)
}

// Dispatch decodes and dispatches an incoming event.
func (o *DataDevice) Dispatch(opcode uint16, d *wire.Decoder) error {
	switch opcode {
	case 0: // data_offer
		a0ID, err := d.Object()
		if err != nil {
			return err
		}
		a0 := &DataOffer{}
		if err := o.Conn().RegisterServer(a0, &a0.Proxy, a0ID); err != nil {
			return err
		}
		if o.OnDataOffer != nil {
			o.OnDataOffer(a0)
		}
		_ = a0
		return nil
	case 1: // enter
		a0, err := d.Uint()
		if err != nil {
			return err
		}
		a1ID, err := d.Object()
		if err != nil {
			return err
		}
		a1, _ := o.Conn().Lookup(a1ID).(*Surface)
		a2, err := d.Fixed()
		if err != nil {
			return err
		}
		a3, err := d.Fixed()
		if err != nil {
			return err
		}
		a4ID, err := d.Object()
		if err != nil {
			return err
		}
		a4, _ := o.Conn().Lookup(a4ID).(*DataOffer)
		if o.OnEnter != nil {
			o.OnEnter(a0, a1, a2, a3, a4)
		}
		_ = a0
		_ = a1
		_ = a2
		_ = a3
		_ = a4
		return nil
	case 2: // leave
		if o.OnLeave != nil {
			o.OnLeave()
		}
		return nil
	case 3: // motion
		a0, err := d.Uint()
		if err != nil {
			return err
		}
		a1, err := d.Fixed()
		if err != nil {
			return err
		}
		a2, err := d.Fixed()
		if err != nil {
			return err
		}
		if o.OnMotion != nil {
			o.OnMotion(a0, a1, a2)
		}
		_ = a0
		_ = a1
		_ = a2
		return nil
	case 4: // drop
		if o.OnDrop != nil {
			o.OnDrop()
		}
		return nil
	case 5: // selection
		a0ID, err := d.Object()
		if err != nil {
			return err
		}
		a0, _ := o.Conn().Lookup(a0ID).(*DataOffer)
		if o.OnSelection != nil {
			o.OnSelection(a0)
		}
		_ = a0
		return nil
	default:
		return fmt.Errorf("unknown opcode %d", opcode)
	}
}

// ---------------------------------------------------------------------------
// wl_data_device_manager
// ---------------------------------------------------------------------------

// DataDeviceManagerName is the Wayland interface name of DataDeviceManager.
const DataDeviceManagerName = "wl_data_device_manager"

// DataDeviceManagerVersion is the highest version of DataDeviceManager supported by these bindings.
const DataDeviceManagerVersion = 3

// DataDeviceManagerDndAction is the dnd_action bitfield enum.
type DataDeviceManagerDndAction uint32

const (
	// DataDeviceManagerDndActionNone: no action
	DataDeviceManagerDndActionNone DataDeviceManagerDndAction = 0
	// DataDeviceManagerDndActionCopy: copy action
	DataDeviceManagerDndActionCopy DataDeviceManagerDndAction = 1
	// DataDeviceManagerDndActionMove: move action
	DataDeviceManagerDndActionMove DataDeviceManagerDndAction = 2
	// DataDeviceManagerDndActionAsk: ask action
	DataDeviceManagerDndActionAsk DataDeviceManagerDndAction = 4
)

// DataDeviceManager is a proxy for the wl_data_device_manager interface.
type DataDeviceManager struct {
	wire.Proxy
}

// Interface returns the Wayland interface name "wl_data_device_manager".
func (*DataDeviceManager) Interface() string { return "wl_data_device_manager" }

// BindDataDeviceManager binds the global named name on the registry to a new DataDeviceManager.
// The version must be <= the advertised version and <= DataDeviceManagerVersion.
func BindDataDeviceManager(r *wire.Registry, name uint32, version uint32) *DataDeviceManager {
	o := &DataDeviceManager{}
	r.Bind(name, DataDeviceManagerName, version, o, &o.Proxy)
	return o
}

// CreateDataSource: create a new data source
func (o *DataDeviceManager) CreateDataSource() *DataSource {
	new_ := &DataSource{}
	o.Conn().RegisterClient(new_, &new_.Proxy)
	e := &wire.Encoder{}
	e.PutUint(new_.ID())
	o.Conn().SendRequest(o, 0, e)
	return new_
}

// GetDataDevice: create a new data device
func (o *DataDeviceManager) GetDataDevice(seat *Seat) *DataDevice {
	new_ := &DataDevice{}
	o.Conn().RegisterClient(new_, &new_.Proxy)
	e := &wire.Encoder{}
	e.PutUint(new_.ID())
	e.PutObject(wire.ObjectID(seat))
	o.Conn().SendRequest(o, 1, e)
	return new_
}

// Dispatch decodes and dispatches an incoming event.
func (o *DataDeviceManager) Dispatch(opcode uint16, d *wire.Decoder) error {
	switch opcode {
	default:
		return fmt.Errorf("unknown opcode %d", opcode)
	}
}

// ---------------------------------------------------------------------------
// wl_shell
// ---------------------------------------------------------------------------

// ShellName is the Wayland interface name of Shell.
const ShellName = "wl_shell"

// ShellVersion is the highest version of Shell supported by these bindings.
const ShellVersion = 1

// ShellError is the error enum.
type ShellError uint32

const (
	// ShellErrorRole: given wl_surface has another role
	ShellErrorRole ShellError = 0
)

// Shell is a proxy for the wl_shell interface.
type Shell struct {
	wire.Proxy
}

// Interface returns the Wayland interface name "wl_shell".
func (*Shell) Interface() string { return "wl_shell" }

// BindShell binds the global named name on the registry to a new Shell.
// The version must be <= the advertised version and <= ShellVersion.
func BindShell(r *wire.Registry, name uint32, version uint32) *Shell {
	o := &Shell{}
	r.Bind(name, ShellName, version, o, &o.Proxy)
	return o
}

// GetShellSurface: create a shell surface from a surface
func (o *Shell) GetShellSurface(surface *Surface) *ShellSurface {
	new_ := &ShellSurface{}
	o.Conn().RegisterClient(new_, &new_.Proxy)
	e := &wire.Encoder{}
	e.PutUint(new_.ID())
	e.PutObject(wire.ObjectID(surface))
	o.Conn().SendRequest(o, 0, e)
	return new_
}

// Dispatch decodes and dispatches an incoming event.
func (o *Shell) Dispatch(opcode uint16, d *wire.Decoder) error {
	switch opcode {
	default:
		return fmt.Errorf("unknown opcode %d", opcode)
	}
}

// ---------------------------------------------------------------------------
// wl_shell_surface
// ---------------------------------------------------------------------------

// ShellSurfaceName is the Wayland interface name of ShellSurface.
const ShellSurfaceName = "wl_shell_surface"

// ShellSurfaceVersion is the highest version of ShellSurface supported by these bindings.
const ShellSurfaceVersion = 1

// ShellSurfaceResize is the resize bitfield enum.
type ShellSurfaceResize uint32

const (
	// ShellSurfaceResizeNone: no edge
	ShellSurfaceResizeNone ShellSurfaceResize = 0
	// ShellSurfaceResizeTop: top edge
	ShellSurfaceResizeTop ShellSurfaceResize = 1
	// ShellSurfaceResizeBottom: bottom edge
	ShellSurfaceResizeBottom ShellSurfaceResize = 2
	// ShellSurfaceResizeLeft: left edge
	ShellSurfaceResizeLeft ShellSurfaceResize = 4
	// ShellSurfaceResizeTopLeft: top and left edges
	ShellSurfaceResizeTopLeft ShellSurfaceResize = 5
	// ShellSurfaceResizeBottomLeft: bottom and left edges
	ShellSurfaceResizeBottomLeft ShellSurfaceResize = 6
	// ShellSurfaceResizeRight: right edge
	ShellSurfaceResizeRight ShellSurfaceResize = 8
	// ShellSurfaceResizeTopRight: top and right edges
	ShellSurfaceResizeTopRight ShellSurfaceResize = 9
	// ShellSurfaceResizeBottomRight: bottom and right edges
	ShellSurfaceResizeBottomRight ShellSurfaceResize = 10
)

// ShellSurfaceTransient is the transient bitfield enum.
type ShellSurfaceTransient uint32

const (
	// ShellSurfaceTransientInactive: do not set keyboard focus
	ShellSurfaceTransientInactive ShellSurfaceTransient = 0x1
)

// ShellSurfaceFullscreenMethod is the fullscreen_method enum.
type ShellSurfaceFullscreenMethod uint32

const (
	// ShellSurfaceFullscreenMethodDefault: no preference, apply default policy
	ShellSurfaceFullscreenMethodDefault ShellSurfaceFullscreenMethod = 0
	// ShellSurfaceFullscreenMethodScale: scale, preserve the surface's aspect ratio and center on output
	ShellSurfaceFullscreenMethodScale ShellSurfaceFullscreenMethod = 1
	// ShellSurfaceFullscreenMethodDriver: switch output mode to the smallest mode that can fit the surface, add black borders to compensate size mismatch
	ShellSurfaceFullscreenMethodDriver ShellSurfaceFullscreenMethod = 2
	// ShellSurfaceFullscreenMethodFill: no upscaling, center on output and add black borders to compensate size mismatch
	ShellSurfaceFullscreenMethodFill ShellSurfaceFullscreenMethod = 3
)

// ShellSurface is a proxy for the wl_shell_surface interface.
type ShellSurface struct {
	wire.Proxy

	// OnPing: ping client
	OnPing func(serial uint32)

	// OnConfigure: suggest resize
	OnConfigure func(edges ShellSurfaceResize, width int32, height int32)

	// OnPopupDone: popup interaction is done
	OnPopupDone func()
}

// Interface returns the Wayland interface name "wl_shell_surface".
func (*ShellSurface) Interface() string { return "wl_shell_surface" }

// BindShellSurface binds the global named name on the registry to a new ShellSurface.
// The version must be <= the advertised version and <= ShellSurfaceVersion.
func BindShellSurface(r *wire.Registry, name uint32, version uint32) *ShellSurface {
	o := &ShellSurface{}
	r.Bind(name, ShellSurfaceName, version, o, &o.Proxy)
	return o
}

// Pong: respond to a ping event
func (o *ShellSurface) Pong(serial uint32) {
	e := &wire.Encoder{}
	e.PutUint(serial)
	o.Conn().SendRequest(o, 0, e)
}

// Move: start an interactive move
func (o *ShellSurface) Move(seat *Seat, serial uint32) {
	e := &wire.Encoder{}
	e.PutObject(wire.ObjectID(seat))
	e.PutUint(serial)
	o.Conn().SendRequest(o, 1, e)
}

// Resize: start an interactive resize
func (o *ShellSurface) Resize(seat *Seat, serial uint32, edges ShellSurfaceResize) {
	e := &wire.Encoder{}
	e.PutObject(wire.ObjectID(seat))
	e.PutUint(serial)
	e.PutUint(uint32(edges))
	o.Conn().SendRequest(o, 2, e)
}

// SetToplevel: make the surface a toplevel surface
func (o *ShellSurface) SetToplevel() {
	e := &wire.Encoder{}
	o.Conn().SendRequest(o, 3, e)
}

// SetTransient: make the surface a transient surface
func (o *ShellSurface) SetTransient(parent *Surface, x int32, y int32, flags ShellSurfaceTransient) {
	e := &wire.Encoder{}
	e.PutObject(wire.ObjectID(parent))
	e.PutInt(x)
	e.PutInt(y)
	e.PutUint(uint32(flags))
	o.Conn().SendRequest(o, 4, e)
}

// SetFullscreen: make the surface a fullscreen surface
func (o *ShellSurface) SetFullscreen(method ShellSurfaceFullscreenMethod, framerate uint32, output *Output) {
	e := &wire.Encoder{}
	e.PutUint(uint32(method))
	e.PutUint(framerate)
	e.PutObject(wire.ObjectID(output))
	o.Conn().SendRequest(o, 5, e)
}

// SetPopup: make the surface a popup surface
func (o *ShellSurface) SetPopup(seat *Seat, serial uint32, parent *Surface, x int32, y int32, flags ShellSurfaceTransient) {
	e := &wire.Encoder{}
	e.PutObject(wire.ObjectID(seat))
	e.PutUint(serial)
	e.PutObject(wire.ObjectID(parent))
	e.PutInt(x)
	e.PutInt(y)
	e.PutUint(uint32(flags))
	o.Conn().SendRequest(o, 6, e)
}

// SetMaximized: make the surface a maximized surface
func (o *ShellSurface) SetMaximized(output *Output) {
	e := &wire.Encoder{}
	e.PutObject(wire.ObjectID(output))
	o.Conn().SendRequest(o, 7, e)
}

// SetTitle: set surface title
func (o *ShellSurface) SetTitle(title string) {
	e := &wire.Encoder{}
	e.PutString(title)
	o.Conn().SendRequest(o, 8, e)
}

// SetClass: set surface class
func (o *ShellSurface) SetClass(class string) {
	e := &wire.Encoder{}
	e.PutString(class)
	o.Conn().SendRequest(o, 9, e)
}

// Dispatch decodes and dispatches an incoming event.
func (o *ShellSurface) Dispatch(opcode uint16, d *wire.Decoder) error {
	switch opcode {
	case 0: // ping
		a0, err := d.Uint()
		if err != nil {
			return err
		}
		if o.OnPing != nil {
			o.OnPing(a0)
		}
		_ = a0
		return nil
	case 1: // configure
		a0Raw, err := d.Uint()
		if err != nil {
			return err
		}
		a0 := ShellSurfaceResize(a0Raw)
		a1, err := d.Int()
		if err != nil {
			return err
		}
		a2, err := d.Int()
		if err != nil {
			return err
		}
		if o.OnConfigure != nil {
			o.OnConfigure(a0, a1, a2)
		}
		_ = a0
		_ = a1
		_ = a2
		return nil
	case 2: // popup_done
		if o.OnPopupDone != nil {
			o.OnPopupDone()
		}
		return nil
	default:
		return fmt.Errorf("unknown opcode %d", opcode)
	}
}

// ---------------------------------------------------------------------------
// wl_surface
// ---------------------------------------------------------------------------

// SurfaceName is the Wayland interface name of Surface.
const SurfaceName = "wl_surface"

// SurfaceVersion is the highest version of Surface supported by these bindings.
const SurfaceVersion = 6

// SurfaceError is the error enum.
type SurfaceError uint32

const (
	// SurfaceErrorInvalidScale: buffer scale value is invalid
	SurfaceErrorInvalidScale SurfaceError = 0
	// SurfaceErrorInvalidTransform: buffer transform value is invalid
	SurfaceErrorInvalidTransform SurfaceError = 1
	// SurfaceErrorInvalidSize: buffer size is invalid
	SurfaceErrorInvalidSize SurfaceError = 2
	// SurfaceErrorInvalidOffset: buffer offset is invalid
	SurfaceErrorInvalidOffset SurfaceError = 3
	// SurfaceErrorDefunctRoleObject: surface was destroyed before its role object
	SurfaceErrorDefunctRoleObject SurfaceError = 4
)

// Surface is a proxy for the wl_surface interface.
type Surface struct {
	wire.Proxy

	// OnEnter: surface enters an output
	OnEnter func(output *Output)

	// OnLeave: surface leaves an output
	OnLeave func(output *Output)

	// OnPreferredBufferScale: preferred buffer scale for the surface
	OnPreferredBufferScale func(factor int32)

	// OnPreferredBufferTransform: preferred buffer transform for the surface
	OnPreferredBufferTransform func(transform OutputTransform)
}

// Interface returns the Wayland interface name "wl_surface".
func (*Surface) Interface() string { return "wl_surface" }

// BindSurface binds the global named name on the registry to a new Surface.
// The version must be <= the advertised version and <= SurfaceVersion.
func BindSurface(r *wire.Registry, name uint32, version uint32) *Surface {
	o := &Surface{}
	r.Bind(name, SurfaceName, version, o, &o.Proxy)
	return o
}

// Destroy: delete surface
// Destroy is a destructor: the object is unusable after this call.
func (o *Surface) Destroy() {
	e := &wire.Encoder{}
	o.Conn().SendRequest(o, 0, e)
	o.Conn().Unregister(o)
}

// Attach: set the surface contents
func (o *Surface) Attach(buffer *Buffer, x int32, y int32) {
	e := &wire.Encoder{}
	e.PutObject(wire.ObjectID(buffer))
	e.PutInt(x)
	e.PutInt(y)
	o.Conn().SendRequest(o, 1, e)
}

// Damage: mark part of the surface damaged
func (o *Surface) Damage(x int32, y int32, width int32, height int32) {
	e := &wire.Encoder{}
	e.PutInt(x)
	e.PutInt(y)
	e.PutInt(width)
	e.PutInt(height)
	o.Conn().SendRequest(o, 2, e)
}

// Frame: request a frame throttling hint
func (o *Surface) Frame() *wire.Callback {
	new_ := &wire.Callback{}
	o.Conn().RegisterClient(new_, &new_.Proxy)
	e := &wire.Encoder{}
	e.PutUint(new_.ID())
	o.Conn().SendRequest(o, 3, e)
	return new_
}

// SetOpaqueRegion: set opaque region
func (o *Surface) SetOpaqueRegion(region *Region) {
	e := &wire.Encoder{}
	e.PutObject(wire.ObjectID(region))
	o.Conn().SendRequest(o, 4, e)
}

// SetInputRegion: set input region
func (o *Surface) SetInputRegion(region *Region) {
	e := &wire.Encoder{}
	e.PutObject(wire.ObjectID(region))
	o.Conn().SendRequest(o, 5, e)
}

// Commit: commit pending surface state
func (o *Surface) Commit() {
	e := &wire.Encoder{}
	o.Conn().SendRequest(o, 6, e)
}

// SetBufferTransform: sets the buffer transformation
func (o *Surface) SetBufferTransform(transform OutputTransform) {
	e := &wire.Encoder{}
	e.PutInt(int32(transform))
	o.Conn().SendRequest(o, 7, e)
}

// SetBufferScale: sets the buffer scaling factor
func (o *Surface) SetBufferScale(scale int32) {
	e := &wire.Encoder{}
	e.PutInt(scale)
	o.Conn().SendRequest(o, 8, e)
}

// DamageBuffer: mark part of the surface damaged using buffer coordinates
func (o *Surface) DamageBuffer(x int32, y int32, width int32, height int32) {
	e := &wire.Encoder{}
	e.PutInt(x)
	e.PutInt(y)
	e.PutInt(width)
	e.PutInt(height)
	o.Conn().SendRequest(o, 9, e)
}

// Offset: set the surface contents offset
func (o *Surface) Offset(x int32, y int32) {
	e := &wire.Encoder{}
	e.PutInt(x)
	e.PutInt(y)
	o.Conn().SendRequest(o, 10, e)
}

// Dispatch decodes and dispatches an incoming event.
func (o *Surface) Dispatch(opcode uint16, d *wire.Decoder) error {
	switch opcode {
	case 0: // enter
		a0ID, err := d.Object()
		if err != nil {
			return err
		}
		a0, _ := o.Conn().Lookup(a0ID).(*Output)
		if o.OnEnter != nil {
			o.OnEnter(a0)
		}
		_ = a0
		return nil
	case 1: // leave
		a0ID, err := d.Object()
		if err != nil {
			return err
		}
		a0, _ := o.Conn().Lookup(a0ID).(*Output)
		if o.OnLeave != nil {
			o.OnLeave(a0)
		}
		_ = a0
		return nil
	case 2: // preferred_buffer_scale
		a0, err := d.Int()
		if err != nil {
			return err
		}
		if o.OnPreferredBufferScale != nil {
			o.OnPreferredBufferScale(a0)
		}
		_ = a0
		return nil
	case 3: // preferred_buffer_transform
		a0Raw, err := d.Uint()
		if err != nil {
			return err
		}
		a0 := OutputTransform(a0Raw)
		if o.OnPreferredBufferTransform != nil {
			o.OnPreferredBufferTransform(a0)
		}
		_ = a0
		return nil
	default:
		return fmt.Errorf("unknown opcode %d", opcode)
	}
}

// ---------------------------------------------------------------------------
// wl_seat
// ---------------------------------------------------------------------------

// SeatName is the Wayland interface name of Seat.
const SeatName = "wl_seat"

// SeatVersion is the highest version of Seat supported by these bindings.
const SeatVersion = 9

// SeatCapability is the capability bitfield enum.
type SeatCapability uint32

const (
	// SeatCapabilityPointer: the seat has pointer devices
	SeatCapabilityPointer SeatCapability = 1
	// SeatCapabilityKeyboard: the seat has one or more keyboards
	SeatCapabilityKeyboard SeatCapability = 2
	// SeatCapabilityTouch: the seat has touch devices
	SeatCapabilityTouch SeatCapability = 4
)

// SeatError is the error enum.
type SeatError uint32

const (
	// SeatErrorMissingCapability: get_pointer, get_keyboard or get_touch called on seat without the matching capability
	SeatErrorMissingCapability SeatError = 0
)

// Seat is a proxy for the wl_seat interface.
type Seat struct {
	wire.Proxy

	// OnCapabilities: seat capabilities changed
	OnCapabilities func(capabilities SeatCapability)

	// OnName: unique identifier for this seat
	OnName func(name string)
}

// Interface returns the Wayland interface name "wl_seat".
func (*Seat) Interface() string { return "wl_seat" }

// BindSeat binds the global named name on the registry to a new Seat.
// The version must be <= the advertised version and <= SeatVersion.
func BindSeat(r *wire.Registry, name uint32, version uint32) *Seat {
	o := &Seat{}
	r.Bind(name, SeatName, version, o, &o.Proxy)
	return o
}

// GetPointer: return pointer object
func (o *Seat) GetPointer() *Pointer {
	new_ := &Pointer{}
	o.Conn().RegisterClient(new_, &new_.Proxy)
	e := &wire.Encoder{}
	e.PutUint(new_.ID())
	o.Conn().SendRequest(o, 0, e)
	return new_
}

// GetKeyboard: return keyboard object
func (o *Seat) GetKeyboard() *Keyboard {
	new_ := &Keyboard{}
	o.Conn().RegisterClient(new_, &new_.Proxy)
	e := &wire.Encoder{}
	e.PutUint(new_.ID())
	o.Conn().SendRequest(o, 1, e)
	return new_
}

// GetTouch: return touch object
func (o *Seat) GetTouch() *Touch {
	new_ := &Touch{}
	o.Conn().RegisterClient(new_, &new_.Proxy)
	e := &wire.Encoder{}
	e.PutUint(new_.ID())
	o.Conn().SendRequest(o, 2, e)
	return new_
}

// Release: release the seat object
// Release is a destructor: the object is unusable after this call.
func (o *Seat) Release() {
	e := &wire.Encoder{}
	o.Conn().SendRequest(o, 3, e)
	o.Conn().Unregister(o)
}

// Dispatch decodes and dispatches an incoming event.
func (o *Seat) Dispatch(opcode uint16, d *wire.Decoder) error {
	switch opcode {
	case 0: // capabilities
		a0Raw, err := d.Uint()
		if err != nil {
			return err
		}
		a0 := SeatCapability(a0Raw)
		if o.OnCapabilities != nil {
			o.OnCapabilities(a0)
		}
		_ = a0
		return nil
	case 1: // name
		a0, _, err := d.String()
		if err != nil {
			return err
		}
		if o.OnName != nil {
			o.OnName(a0)
		}
		_ = a0
		return nil
	default:
		return fmt.Errorf("unknown opcode %d", opcode)
	}
}

// ---------------------------------------------------------------------------
// wl_pointer
// ---------------------------------------------------------------------------

// PointerName is the Wayland interface name of Pointer.
const PointerName = "wl_pointer"

// PointerVersion is the highest version of Pointer supported by these bindings.
const PointerVersion = 9

// PointerError is the error enum.
type PointerError uint32

const (
	// PointerErrorRole: given wl_surface has another role
	PointerErrorRole PointerError = 0
)

// PointerButtonState is the button_state enum.
type PointerButtonState uint32

const (
	// PointerButtonStateReleased: the button is not pressed
	PointerButtonStateReleased PointerButtonState = 0
	// PointerButtonStatePressed: the button is pressed
	PointerButtonStatePressed PointerButtonState = 1
)

// PointerAxis is the axis enum.
type PointerAxis uint32

const (
	// PointerAxisVerticalScroll: vertical axis
	PointerAxisVerticalScroll PointerAxis = 0
	// PointerAxisHorizontalScroll: horizontal axis
	PointerAxisHorizontalScroll PointerAxis = 1
)

// PointerAxisSource is the axis_source enum.
type PointerAxisSource uint32

const (
	// PointerAxisSourceWheel: a physical wheel rotation
	PointerAxisSourceWheel PointerAxisSource = 0
	// PointerAxisSourceFinger: finger on a touch surface
	PointerAxisSourceFinger PointerAxisSource = 1
	// PointerAxisSourceContinuous: continuous coordinate space
	PointerAxisSourceContinuous PointerAxisSource = 2
	// PointerAxisSourceWheelTilt: a physical wheel tilt
	PointerAxisSourceWheelTilt PointerAxisSource = 3
)

// PointerAxisRelativeDirection is the axis_relative_direction enum.
type PointerAxisRelativeDirection uint32

const (
	// PointerAxisRelativeDirectionIdentical: physical motion matches axis direction
	PointerAxisRelativeDirectionIdentical PointerAxisRelativeDirection = 0
	// PointerAxisRelativeDirectionInverted: physical motion is the inverse of the axis direction
	PointerAxisRelativeDirectionInverted PointerAxisRelativeDirection = 1
)

// Pointer is a proxy for the wl_pointer interface.
type Pointer struct {
	wire.Proxy

	// OnEnter: enter event
	OnEnter func(serial uint32, surface *Surface, surfaceX wire.Fixed, surfaceY wire.Fixed)

	// OnLeave: leave event
	OnLeave func(serial uint32, surface *Surface)

	// OnMotion: pointer motion event
	OnMotion func(time uint32, surfaceX wire.Fixed, surfaceY wire.Fixed)

	// OnButton: pointer button event
	OnButton func(serial uint32, time uint32, button uint32, state PointerButtonState)

	// OnAxis: axis event
	OnAxis func(time uint32, axis PointerAxis, value wire.Fixed)

	// OnFrame: end of a pointer event sequence
	OnFrame func()

	// OnAxisSource: axis source event
	OnAxisSource func(axisSource PointerAxisSource)

	// OnAxisStop: axis stop event
	OnAxisStop func(time uint32, axis PointerAxis)

	// OnAxisDiscrete: axis click event
	OnAxisDiscrete func(axis PointerAxis, discrete int32)

	// OnAxisValue120: axis high-resolution scroll event
	OnAxisValue120 func(axis PointerAxis, value120 int32)

	// OnAxisRelativeDirection: axis relative physical direction event
	OnAxisRelativeDirection func(axis PointerAxis, direction PointerAxisRelativeDirection)
}

// Interface returns the Wayland interface name "wl_pointer".
func (*Pointer) Interface() string { return "wl_pointer" }

// BindPointer binds the global named name on the registry to a new Pointer.
// The version must be <= the advertised version and <= PointerVersion.
func BindPointer(r *wire.Registry, name uint32, version uint32) *Pointer {
	o := &Pointer{}
	r.Bind(name, PointerName, version, o, &o.Proxy)
	return o
}

// SetCursor: set the pointer surface
func (o *Pointer) SetCursor(serial uint32, surface *Surface, hotspotX int32, hotspotY int32) {
	e := &wire.Encoder{}
	e.PutUint(serial)
	e.PutObject(wire.ObjectID(surface))
	e.PutInt(hotspotX)
	e.PutInt(hotspotY)
	o.Conn().SendRequest(o, 0, e)
}

// Release: release the pointer object
// Release is a destructor: the object is unusable after this call.
func (o *Pointer) Release() {
	e := &wire.Encoder{}
	o.Conn().SendRequest(o, 1, e)
	o.Conn().Unregister(o)
}

// Dispatch decodes and dispatches an incoming event.
func (o *Pointer) Dispatch(opcode uint16, d *wire.Decoder) error {
	switch opcode {
	case 0: // enter
		a0, err := d.Uint()
		if err != nil {
			return err
		}
		a1ID, err := d.Object()
		if err != nil {
			return err
		}
		a1, _ := o.Conn().Lookup(a1ID).(*Surface)
		a2, err := d.Fixed()
		if err != nil {
			return err
		}
		a3, err := d.Fixed()
		if err != nil {
			return err
		}
		if o.OnEnter != nil {
			o.OnEnter(a0, a1, a2, a3)
		}
		_ = a0
		_ = a1
		_ = a2
		_ = a3
		return nil
	case 1: // leave
		a0, err := d.Uint()
		if err != nil {
			return err
		}
		a1ID, err := d.Object()
		if err != nil {
			return err
		}
		a1, _ := o.Conn().Lookup(a1ID).(*Surface)
		if o.OnLeave != nil {
			o.OnLeave(a0, a1)
		}
		_ = a0
		_ = a1
		return nil
	case 2: // motion
		a0, err := d.Uint()
		if err != nil {
			return err
		}
		a1, err := d.Fixed()
		if err != nil {
			return err
		}
		a2, err := d.Fixed()
		if err != nil {
			return err
		}
		if o.OnMotion != nil {
			o.OnMotion(a0, a1, a2)
		}
		_ = a0
		_ = a1
		_ = a2
		return nil
	case 3: // button
		a0, err := d.Uint()
		if err != nil {
			return err
		}
		a1, err := d.Uint()
		if err != nil {
			return err
		}
		a2, err := d.Uint()
		if err != nil {
			return err
		}
		a3Raw, err := d.Uint()
		if err != nil {
			return err
		}
		a3 := PointerButtonState(a3Raw)
		if o.OnButton != nil {
			o.OnButton(a0, a1, a2, a3)
		}
		_ = a0
		_ = a1
		_ = a2
		_ = a3
		return nil
	case 4: // axis
		a0, err := d.Uint()
		if err != nil {
			return err
		}
		a1Raw, err := d.Uint()
		if err != nil {
			return err
		}
		a1 := PointerAxis(a1Raw)
		a2, err := d.Fixed()
		if err != nil {
			return err
		}
		if o.OnAxis != nil {
			o.OnAxis(a0, a1, a2)
		}
		_ = a0
		_ = a1
		_ = a2
		return nil
	case 5: // frame
		if o.OnFrame != nil {
			o.OnFrame()
		}
		return nil
	case 6: // axis_source
		a0Raw, err := d.Uint()
		if err != nil {
			return err
		}
		a0 := PointerAxisSource(a0Raw)
		if o.OnAxisSource != nil {
			o.OnAxisSource(a0)
		}
		_ = a0
		return nil
	case 7: // axis_stop
		a0, err := d.Uint()
		if err != nil {
			return err
		}
		a1Raw, err := d.Uint()
		if err != nil {
			return err
		}
		a1 := PointerAxis(a1Raw)
		if o.OnAxisStop != nil {
			o.OnAxisStop(a0, a1)
		}
		_ = a0
		_ = a1
		return nil
	case 8: // axis_discrete
		a0Raw, err := d.Uint()
		if err != nil {
			return err
		}
		a0 := PointerAxis(a0Raw)
		a1, err := d.Int()
		if err != nil {
			return err
		}
		if o.OnAxisDiscrete != nil {
			o.OnAxisDiscrete(a0, a1)
		}
		_ = a0
		_ = a1
		return nil
	case 9: // axis_value120
		a0Raw, err := d.Uint()
		if err != nil {
			return err
		}
		a0 := PointerAxis(a0Raw)
		a1, err := d.Int()
		if err != nil {
			return err
		}
		if o.OnAxisValue120 != nil {
			o.OnAxisValue120(a0, a1)
		}
		_ = a0
		_ = a1
		return nil
	case 10: // axis_relative_direction
		a0Raw, err := d.Uint()
		if err != nil {
			return err
		}
		a0 := PointerAxis(a0Raw)
		a1Raw, err := d.Uint()
		if err != nil {
			return err
		}
		a1 := PointerAxisRelativeDirection(a1Raw)
		if o.OnAxisRelativeDirection != nil {
			o.OnAxisRelativeDirection(a0, a1)
		}
		_ = a0
		_ = a1
		return nil
	default:
		return fmt.Errorf("unknown opcode %d", opcode)
	}
}

// ---------------------------------------------------------------------------
// wl_keyboard
// ---------------------------------------------------------------------------

// KeyboardName is the Wayland interface name of Keyboard.
const KeyboardName = "wl_keyboard"

// KeyboardVersion is the highest version of Keyboard supported by these bindings.
const KeyboardVersion = 9

// KeyboardKeymapFormat is the keymap_format enum.
type KeyboardKeymapFormat uint32

const (
	// KeyboardKeymapFormatNoKeymap: no keymap; client must understand how to interpret the raw keycode
	KeyboardKeymapFormatNoKeymap KeyboardKeymapFormat = 0
	// KeyboardKeymapFormatXkbV1: libxkbcommon compatible, null-terminated string; to determine the xkb keycode, clients must add 8 to the key event keycode
	KeyboardKeymapFormatXkbV1 KeyboardKeymapFormat = 1
)

// KeyboardKeyState is the key_state enum.
type KeyboardKeyState uint32

const (
	// KeyboardKeyStateReleased: key is not pressed
	KeyboardKeyStateReleased KeyboardKeyState = 0
	// KeyboardKeyStatePressed: key is pressed
	KeyboardKeyStatePressed KeyboardKeyState = 1
)

// Keyboard is a proxy for the wl_keyboard interface.
type Keyboard struct {
	wire.Proxy

	// OnKeymap: keyboard mapping
	OnKeymap func(format KeyboardKeymapFormat, fd int, size uint32)

	// OnEnter: enter event
	OnEnter func(serial uint32, surface *Surface, keys []byte)

	// OnLeave: leave event
	OnLeave func(serial uint32, surface *Surface)

	// OnKey: key event
	OnKey func(serial uint32, time uint32, key uint32, state KeyboardKeyState)

	// OnModifiers: modifier and group state
	OnModifiers func(serial uint32, modsDepressed uint32, modsLatched uint32, modsLocked uint32, group uint32)

	// OnRepeatInfo: repeat rate and delay
	OnRepeatInfo func(rate int32, delay int32)
}

// Interface returns the Wayland interface name "wl_keyboard".
func (*Keyboard) Interface() string { return "wl_keyboard" }

// BindKeyboard binds the global named name on the registry to a new Keyboard.
// The version must be <= the advertised version and <= KeyboardVersion.
func BindKeyboard(r *wire.Registry, name uint32, version uint32) *Keyboard {
	o := &Keyboard{}
	r.Bind(name, KeyboardName, version, o, &o.Proxy)
	return o
}

// Release: release the keyboard object
// Release is a destructor: the object is unusable after this call.
func (o *Keyboard) Release() {
	e := &wire.Encoder{}
	o.Conn().SendRequest(o, 0, e)
	o.Conn().Unregister(o)
}

// Dispatch decodes and dispatches an incoming event.
func (o *Keyboard) Dispatch(opcode uint16, d *wire.Decoder) error {
	switch opcode {
	case 0: // keymap
		a0Raw, err := d.Uint()
		if err != nil {
			return err
		}
		a0 := KeyboardKeymapFormat(a0Raw)
		a1, err := d.Fd()
		if err != nil {
			return err
		}
		a2, err := d.Uint()
		if err != nil {
			return err
		}
		if o.OnKeymap != nil {
			o.OnKeymap(a0, a1, a2)
		}
		_ = a0
		_ = a1
		_ = a2
		return nil
	case 1: // enter
		a0, err := d.Uint()
		if err != nil {
			return err
		}
		a1ID, err := d.Object()
		if err != nil {
			return err
		}
		a1, _ := o.Conn().Lookup(a1ID).(*Surface)
		a2Raw, err := d.Array()
		if err != nil {
			return err
		}
		a2 := append([]byte(nil), a2Raw...)
		if o.OnEnter != nil {
			o.OnEnter(a0, a1, a2)
		}
		_ = a0
		_ = a1
		_ = a2
		return nil
	case 2: // leave
		a0, err := d.Uint()
		if err != nil {
			return err
		}
		a1ID, err := d.Object()
		if err != nil {
			return err
		}
		a1, _ := o.Conn().Lookup(a1ID).(*Surface)
		if o.OnLeave != nil {
			o.OnLeave(a0, a1)
		}
		_ = a0
		_ = a1
		return nil
	case 3: // key
		a0, err := d.Uint()
		if err != nil {
			return err
		}
		a1, err := d.Uint()
		if err != nil {
			return err
		}
		a2, err := d.Uint()
		if err != nil {
			return err
		}
		a3Raw, err := d.Uint()
		if err != nil {
			return err
		}
		a3 := KeyboardKeyState(a3Raw)
		if o.OnKey != nil {
			o.OnKey(a0, a1, a2, a3)
		}
		_ = a0
		_ = a1
		_ = a2
		_ = a3
		return nil
	case 4: // modifiers
		a0, err := d.Uint()
		if err != nil {
			return err
		}
		a1, err := d.Uint()
		if err != nil {
			return err
		}
		a2, err := d.Uint()
		if err != nil {
			return err
		}
		a3, err := d.Uint()
		if err != nil {
			return err
		}
		a4, err := d.Uint()
		if err != nil {
			return err
		}
		if o.OnModifiers != nil {
			o.OnModifiers(a0, a1, a2, a3, a4)
		}
		_ = a0
		_ = a1
		_ = a2
		_ = a3
		_ = a4
		return nil
	case 5: // repeat_info
		a0, err := d.Int()
		if err != nil {
			return err
		}
		a1, err := d.Int()
		if err != nil {
			return err
		}
		if o.OnRepeatInfo != nil {
			o.OnRepeatInfo(a0, a1)
		}
		_ = a0
		_ = a1
		return nil
	default:
		return fmt.Errorf("unknown opcode %d", opcode)
	}
}

// ---------------------------------------------------------------------------
// wl_touch
// ---------------------------------------------------------------------------

// TouchName is the Wayland interface name of Touch.
const TouchName = "wl_touch"

// TouchVersion is the highest version of Touch supported by these bindings.
const TouchVersion = 9

// Touch is a proxy for the wl_touch interface.
type Touch struct {
	wire.Proxy

	// OnDown: touch down event and beginning of a touch sequence
	OnDown func(serial uint32, time uint32, surface *Surface, id int32, x wire.Fixed, y wire.Fixed)

	// OnUp: end of a touch event sequence
	OnUp func(serial uint32, time uint32, id int32)

	// OnMotion: update of touch point coordinates
	OnMotion func(time uint32, id int32, x wire.Fixed, y wire.Fixed)

	// OnFrame: end of touch frame event
	OnFrame func()

	// OnCancel: touch session cancelled
	OnCancel func()

	// OnShape: update shape of touch point
	OnShape func(id int32, major wire.Fixed, minor wire.Fixed)

	// OnOrientation: update orientation of touch point
	OnOrientation func(id int32, orientation wire.Fixed)
}

// Interface returns the Wayland interface name "wl_touch".
func (*Touch) Interface() string { return "wl_touch" }

// BindTouch binds the global named name on the registry to a new Touch.
// The version must be <= the advertised version and <= TouchVersion.
func BindTouch(r *wire.Registry, name uint32, version uint32) *Touch {
	o := &Touch{}
	r.Bind(name, TouchName, version, o, &o.Proxy)
	return o
}

// Release: release the touch object
// Release is a destructor: the object is unusable after this call.
func (o *Touch) Release() {
	e := &wire.Encoder{}
	o.Conn().SendRequest(o, 0, e)
	o.Conn().Unregister(o)
}

// Dispatch decodes and dispatches an incoming event.
func (o *Touch) Dispatch(opcode uint16, d *wire.Decoder) error {
	switch opcode {
	case 0: // down
		a0, err := d.Uint()
		if err != nil {
			return err
		}
		a1, err := d.Uint()
		if err != nil {
			return err
		}
		a2ID, err := d.Object()
		if err != nil {
			return err
		}
		a2, _ := o.Conn().Lookup(a2ID).(*Surface)
		a3, err := d.Int()
		if err != nil {
			return err
		}
		a4, err := d.Fixed()
		if err != nil {
			return err
		}
		a5, err := d.Fixed()
		if err != nil {
			return err
		}
		if o.OnDown != nil {
			o.OnDown(a0, a1, a2, a3, a4, a5)
		}
		_ = a0
		_ = a1
		_ = a2
		_ = a3
		_ = a4
		_ = a5
		return nil
	case 1: // up
		a0, err := d.Uint()
		if err != nil {
			return err
		}
		a1, err := d.Uint()
		if err != nil {
			return err
		}
		a2, err := d.Int()
		if err != nil {
			return err
		}
		if o.OnUp != nil {
			o.OnUp(a0, a1, a2)
		}
		_ = a0
		_ = a1
		_ = a2
		return nil
	case 2: // motion
		a0, err := d.Uint()
		if err != nil {
			return err
		}
		a1, err := d.Int()
		if err != nil {
			return err
		}
		a2, err := d.Fixed()
		if err != nil {
			return err
		}
		a3, err := d.Fixed()
		if err != nil {
			return err
		}
		if o.OnMotion != nil {
			o.OnMotion(a0, a1, a2, a3)
		}
		_ = a0
		_ = a1
		_ = a2
		_ = a3
		return nil
	case 3: // frame
		if o.OnFrame != nil {
			o.OnFrame()
		}
		return nil
	case 4: // cancel
		if o.OnCancel != nil {
			o.OnCancel()
		}
		return nil
	case 5: // shape
		a0, err := d.Int()
		if err != nil {
			return err
		}
		a1, err := d.Fixed()
		if err != nil {
			return err
		}
		a2, err := d.Fixed()
		if err != nil {
			return err
		}
		if o.OnShape != nil {
			o.OnShape(a0, a1, a2)
		}
		_ = a0
		_ = a1
		_ = a2
		return nil
	case 6: // orientation
		a0, err := d.Int()
		if err != nil {
			return err
		}
		a1, err := d.Fixed()
		if err != nil {
			return err
		}
		if o.OnOrientation != nil {
			o.OnOrientation(a0, a1)
		}
		_ = a0
		_ = a1
		return nil
	default:
		return fmt.Errorf("unknown opcode %d", opcode)
	}
}

// ---------------------------------------------------------------------------
// wl_output
// ---------------------------------------------------------------------------

// OutputName is the Wayland interface name of Output.
const OutputName = "wl_output"

// OutputVersion is the highest version of Output supported by these bindings.
const OutputVersion = 4

// OutputSubpixel is the subpixel enum.
type OutputSubpixel uint32

const (
	// OutputSubpixelUnknown: unknown geometry
	OutputSubpixelUnknown OutputSubpixel = 0
	// OutputSubpixelNone: no geometry
	OutputSubpixelNone OutputSubpixel = 1
	// OutputSubpixelHorizontalRgb: horizontal RGB
	OutputSubpixelHorizontalRgb OutputSubpixel = 2
	// OutputSubpixelHorizontalBgr: horizontal BGR
	OutputSubpixelHorizontalBgr OutputSubpixel = 3
	// OutputSubpixelVerticalRgb: vertical RGB
	OutputSubpixelVerticalRgb OutputSubpixel = 4
	// OutputSubpixelVerticalBgr: vertical BGR
	OutputSubpixelVerticalBgr OutputSubpixel = 5
)

// OutputTransform is the transform enum.
type OutputTransform uint32

const (
	// OutputTransformNormal: no transform
	OutputTransformNormal OutputTransform = 0
	// OutputTransform_90: 90 degrees counter-clockwise
	OutputTransform_90 OutputTransform = 1
	// OutputTransform_180: 180 degrees counter-clockwise
	OutputTransform_180 OutputTransform = 2
	// OutputTransform_270: 270 degrees counter-clockwise
	OutputTransform_270 OutputTransform = 3
	// OutputTransformFlipped: 180 degree flip around a vertical axis
	OutputTransformFlipped OutputTransform = 4
	// OutputTransformFlipped90: flip and rotate 90 degrees counter-clockwise
	OutputTransformFlipped90 OutputTransform = 5
	// OutputTransformFlipped180: flip and rotate 180 degrees counter-clockwise
	OutputTransformFlipped180 OutputTransform = 6
	// OutputTransformFlipped270: flip and rotate 270 degrees counter-clockwise
	OutputTransformFlipped270 OutputTransform = 7
)

// OutputMode is the mode bitfield enum.
type OutputMode uint32

const (
	// OutputModeCurrent: indicates this is the current mode
	OutputModeCurrent OutputMode = 0x1
	// OutputModePreferred: indicates this is the preferred mode
	OutputModePreferred OutputMode = 0x2
)

// Output is a proxy for the wl_output interface.
type Output struct {
	wire.Proxy

	// OnGeometry: properties of the output
	OnGeometry func(x int32, y int32, physicalWidth int32, physicalHeight int32, subpixel OutputSubpixel, make string, model string, transform OutputTransform)

	// OnMode: advertise available modes for the output
	OnMode func(flags OutputMode, width int32, height int32, refresh int32)

	// OnDone: sent all information about output
	OnDone func()

	// OnScale: output scaling properties
	OnScale func(factor int32)

	// OnName: name of this output
	OnName func(name string)

	// OnDescription: human-readable description of this output
	OnDescription func(description string)
}

// Interface returns the Wayland interface name "wl_output".
func (*Output) Interface() string { return "wl_output" }

// BindOutput binds the global named name on the registry to a new Output.
// The version must be <= the advertised version and <= OutputVersion.
func BindOutput(r *wire.Registry, name uint32, version uint32) *Output {
	o := &Output{}
	r.Bind(name, OutputName, version, o, &o.Proxy)
	return o
}

// Release: release the output object
// Release is a destructor: the object is unusable after this call.
func (o *Output) Release() {
	e := &wire.Encoder{}
	o.Conn().SendRequest(o, 0, e)
	o.Conn().Unregister(o)
}

// Dispatch decodes and dispatches an incoming event.
func (o *Output) Dispatch(opcode uint16, d *wire.Decoder) error {
	switch opcode {
	case 0: // geometry
		a0, err := d.Int()
		if err != nil {
			return err
		}
		a1, err := d.Int()
		if err != nil {
			return err
		}
		a2, err := d.Int()
		if err != nil {
			return err
		}
		a3, err := d.Int()
		if err != nil {
			return err
		}
		a4Raw, err := d.Int()
		if err != nil {
			return err
		}
		a4 := OutputSubpixel(a4Raw)
		a5, _, err := d.String()
		if err != nil {
			return err
		}
		a6, _, err := d.String()
		if err != nil {
			return err
		}
		a7Raw, err := d.Int()
		if err != nil {
			return err
		}
		a7 := OutputTransform(a7Raw)
		if o.OnGeometry != nil {
			o.OnGeometry(a0, a1, a2, a3, a4, a5, a6, a7)
		}
		_ = a0
		_ = a1
		_ = a2
		_ = a3
		_ = a4
		_ = a5
		_ = a6
		_ = a7
		return nil
	case 1: // mode
		a0Raw, err := d.Uint()
		if err != nil {
			return err
		}
		a0 := OutputMode(a0Raw)
		a1, err := d.Int()
		if err != nil {
			return err
		}
		a2, err := d.Int()
		if err != nil {
			return err
		}
		a3, err := d.Int()
		if err != nil {
			return err
		}
		if o.OnMode != nil {
			o.OnMode(a0, a1, a2, a3)
		}
		_ = a0
		_ = a1
		_ = a2
		_ = a3
		return nil
	case 2: // done
		if o.OnDone != nil {
			o.OnDone()
		}
		return nil
	case 3: // scale
		a0, err := d.Int()
		if err != nil {
			return err
		}
		if o.OnScale != nil {
			o.OnScale(a0)
		}
		_ = a0
		return nil
	case 4: // name
		a0, _, err := d.String()
		if err != nil {
			return err
		}
		if o.OnName != nil {
			o.OnName(a0)
		}
		_ = a0
		return nil
	case 5: // description
		a0, _, err := d.String()
		if err != nil {
			return err
		}
		if o.OnDescription != nil {
			o.OnDescription(a0)
		}
		_ = a0
		return nil
	default:
		return fmt.Errorf("unknown opcode %d", opcode)
	}
}

// ---------------------------------------------------------------------------
// wl_region
// ---------------------------------------------------------------------------

// RegionName is the Wayland interface name of Region.
const RegionName = "wl_region"

// RegionVersion is the highest version of Region supported by these bindings.
const RegionVersion = 1

// Region is a proxy for the wl_region interface.
type Region struct {
	wire.Proxy
}

// Interface returns the Wayland interface name "wl_region".
func (*Region) Interface() string { return "wl_region" }

// BindRegion binds the global named name on the registry to a new Region.
// The version must be <= the advertised version and <= RegionVersion.
func BindRegion(r *wire.Registry, name uint32, version uint32) *Region {
	o := &Region{}
	r.Bind(name, RegionName, version, o, &o.Proxy)
	return o
}

// Destroy: destroy region
// Destroy is a destructor: the object is unusable after this call.
func (o *Region) Destroy() {
	e := &wire.Encoder{}
	o.Conn().SendRequest(o, 0, e)
	o.Conn().Unregister(o)
}

// Add: add rectangle to region
func (o *Region) Add(x int32, y int32, width int32, height int32) {
	e := &wire.Encoder{}
	e.PutInt(x)
	e.PutInt(y)
	e.PutInt(width)
	e.PutInt(height)
	o.Conn().SendRequest(o, 1, e)
}

// Subtract: subtract rectangle from region
func (o *Region) Subtract(x int32, y int32, width int32, height int32) {
	e := &wire.Encoder{}
	e.PutInt(x)
	e.PutInt(y)
	e.PutInt(width)
	e.PutInt(height)
	o.Conn().SendRequest(o, 2, e)
}

// Dispatch decodes and dispatches an incoming event.
func (o *Region) Dispatch(opcode uint16, d *wire.Decoder) error {
	switch opcode {
	default:
		return fmt.Errorf("unknown opcode %d", opcode)
	}
}

// ---------------------------------------------------------------------------
// wl_subcompositor
// ---------------------------------------------------------------------------

// SubcompositorName is the Wayland interface name of Subcompositor.
const SubcompositorName = "wl_subcompositor"

// SubcompositorVersion is the highest version of Subcompositor supported by these bindings.
const SubcompositorVersion = 1

// SubcompositorError is the error enum.
type SubcompositorError uint32

const (
	// SubcompositorErrorBadSurface: the to-be sub-surface is invalid
	SubcompositorErrorBadSurface SubcompositorError = 0
	// SubcompositorErrorBadParent: the to-be sub-surface parent is invalid
	SubcompositorErrorBadParent SubcompositorError = 1
)

// Subcompositor is a proxy for the wl_subcompositor interface.
type Subcompositor struct {
	wire.Proxy
}

// Interface returns the Wayland interface name "wl_subcompositor".
func (*Subcompositor) Interface() string { return "wl_subcompositor" }

// BindSubcompositor binds the global named name on the registry to a new Subcompositor.
// The version must be <= the advertised version and <= SubcompositorVersion.
func BindSubcompositor(r *wire.Registry, name uint32, version uint32) *Subcompositor {
	o := &Subcompositor{}
	r.Bind(name, SubcompositorName, version, o, &o.Proxy)
	return o
}

// Destroy: unbind from the subcompositor interface
// Destroy is a destructor: the object is unusable after this call.
func (o *Subcompositor) Destroy() {
	e := &wire.Encoder{}
	o.Conn().SendRequest(o, 0, e)
	o.Conn().Unregister(o)
}

// GetSubsurface: give a surface the role sub-surface
func (o *Subcompositor) GetSubsurface(surface *Surface, parent *Surface) *Subsurface {
	new_ := &Subsurface{}
	o.Conn().RegisterClient(new_, &new_.Proxy)
	e := &wire.Encoder{}
	e.PutUint(new_.ID())
	e.PutObject(wire.ObjectID(surface))
	e.PutObject(wire.ObjectID(parent))
	o.Conn().SendRequest(o, 1, e)
	return new_
}

// Dispatch decodes and dispatches an incoming event.
func (o *Subcompositor) Dispatch(opcode uint16, d *wire.Decoder) error {
	switch opcode {
	default:
		return fmt.Errorf("unknown opcode %d", opcode)
	}
}

// ---------------------------------------------------------------------------
// wl_subsurface
// ---------------------------------------------------------------------------

// SubsurfaceName is the Wayland interface name of Subsurface.
const SubsurfaceName = "wl_subsurface"

// SubsurfaceVersion is the highest version of Subsurface supported by these bindings.
const SubsurfaceVersion = 1

// SubsurfaceError is the error enum.
type SubsurfaceError uint32

const (
	// SubsurfaceErrorBadSurface: wl_surface is not a sibling or the parent
	SubsurfaceErrorBadSurface SubsurfaceError = 0
)

// Subsurface is a proxy for the wl_subsurface interface.
type Subsurface struct {
	wire.Proxy
}

// Interface returns the Wayland interface name "wl_subsurface".
func (*Subsurface) Interface() string { return "wl_subsurface" }

// BindSubsurface binds the global named name on the registry to a new Subsurface.
// The version must be <= the advertised version and <= SubsurfaceVersion.
func BindSubsurface(r *wire.Registry, name uint32, version uint32) *Subsurface {
	o := &Subsurface{}
	r.Bind(name, SubsurfaceName, version, o, &o.Proxy)
	return o
}

// Destroy: remove sub-surface interface
// Destroy is a destructor: the object is unusable after this call.
func (o *Subsurface) Destroy() {
	e := &wire.Encoder{}
	o.Conn().SendRequest(o, 0, e)
	o.Conn().Unregister(o)
}

// SetPosition: reposition the sub-surface
func (o *Subsurface) SetPosition(x int32, y int32) {
	e := &wire.Encoder{}
	e.PutInt(x)
	e.PutInt(y)
	o.Conn().SendRequest(o, 1, e)
}

// PlaceAbove: restack the sub-surface
func (o *Subsurface) PlaceAbove(sibling *Surface) {
	e := &wire.Encoder{}
	e.PutObject(wire.ObjectID(sibling))
	o.Conn().SendRequest(o, 2, e)
}

// PlaceBelow: restack the sub-surface
func (o *Subsurface) PlaceBelow(sibling *Surface) {
	e := &wire.Encoder{}
	e.PutObject(wire.ObjectID(sibling))
	o.Conn().SendRequest(o, 3, e)
}

// SetSync: set sub-surface to synchronized mode
func (o *Subsurface) SetSync() {
	e := &wire.Encoder{}
	o.Conn().SendRequest(o, 4, e)
}

// SetDesync: set sub-surface to desynchronized mode
func (o *Subsurface) SetDesync() {
	e := &wire.Encoder{}
	o.Conn().SendRequest(o, 5, e)
}

// Dispatch decodes and dispatches an incoming event.
func (o *Subsurface) Dispatch(opcode uint16, d *wire.Decoder) error {
	switch opcode {
	default:
		return fmt.Errorf("unknown opcode %d", opcode)
	}
}
